### ISSUE TITLE
put this on the CPAN

### ISSUE THREAD

**Issue by papercreatures** [pnu/Plack-Middleware-Cache-CHI#1]
This works really well unlike it's namesake. I'd suggest renaming it Plack::Middleware::CacheCHI or something.

Thanks!

**Comment by pnu** [comment]
Ok, thanks for input!

I was hoping to integrate the full HTTP cache validation (ie. what I had in devel branch, modelled after the Rack Cache module) before publishing it, but ran out of tuits. We've had this in production use for couple of years, so yes it's usable. I'll rename it to ...::Cache::CHI and publish to CPAN soon.

**Comment by espizo** [comment]
Hi.

Any news here? :)

**Comment by pnu** [comment]
Thanks for caring. Here it is. :smile: I also wrote some basic tests, but contributions are welcome.

https://metacpan.org/source/PNU/Plack-Middleware-Cache-CHI-0.102

**Comment by espizo** [comment]
That was quick!

Thanks for sharing :smile:
